FROM node:20-alpine

WORKDIR /app

COPY package.json ./
RUN npm install

COPY docker-entrypoint.dev.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.dev.sh

COPY . .

EXPOSE 5000

ENTRYPOINT ["docker-entrypoint.dev.sh"]
CMD ["npm", "run", "dev"]
